### ISSUE TITLE
Thoughts on how to make package.yml happen.

### ISSUE THREAD

**Issue by reggi** [keithamus/npm-scripts-example#1]
I know this is crazy but I found a pretty paradoxical bug.

Because we'll be spending more time in our `package.json` file, I thought lets use yml instead.

In order to run the scrips we need the `.json` version. and we'd end up writing in the `.yml` one but then dependencies would be written to the `.json` one. This seems like a head ache, we'd need a double watch, and I just feel like it would be an infinite loop.

```
{
  "name": "example",
  "version": "0.0.1",
  "main": "index.js",
  "scripts": {
    "jsontoyml": "ruby -ryaml -rjson -e 'puts YAML.dump(JSON.parse(STDIN.read))'",
    "ymltojson": "ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))'",
    "packagetojson": "npm run ymltojson -- < ./package.yaml > ./package.json",
    "watch:packageyml": "onchange ./package.yml -- npm ymltojson -- < ./package.yml > ./package.json'"
  }
}
```

```

---
name: example
version: 0.0.1
main: index.js
scripts:
  jsontoyml: ruby -ryaml -rjson -e 'puts YAML.dump(JSON.parse(STDIN.read))'
  ymltojson: ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))'
  packagetojson: npm run ymltojson -- < ./package.yaml > ./package.json
  watch:packageyml: onchange ./package.yml -- npm ymltojson -- < ./package.yml > ./package.json'
```

The closest thing is [npm-yaml](https://www.npmjs.com/package/npm-yaml) I couldn't get it to work.
